name: Test Black Duck Scan


on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

env:
  REPO_REF: ${{ github.ref }}

jobs:
  duckify:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Last tag
        id: extract_last_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: unknown

      - name: Extract version main
        if: env.REPO_REF == 'refs/heads/main' ||
              env.REPO_REF == 'refs/heads/master'
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${REPO_REF#refs/heads/}_${{ steps.extract_last_tag.outputs.tag }})"
        id: extract_version_main

      - name: Extract version release
        if: startsWith(env.REPO_REF, 'refs/heads/hotfix/') ||
              startsWith(env.REPO_REF, 'refs/heads/release')
        shell: bash
        run: echo "##[set-output name=version;]release"
        id: extract_version_release

      - name: Extract version dev
        if: startsWith(env.REPO_REF, 'refs/heads/develop') ||
              startsWith(env.REPO_REF, 'refs/heads/feature/')
        shell: bash
        run: echo "##[set-output name=version;]develop"
        id: extract_version_dev

      - name: Check output
        shell: bash
        run: |
          echo "Version1 is:" ${{ steps.extract_version_main.outputs.version }}${{ steps.extract_version_release.outputs.version }}${{ steps.extract_version_dev.outputs.version }}
          echo "Version2 is:" "${{ steps.extract_last_tag.outputs.tag}}"
          echo "ref :" "${{ github.ref }}"
          echo "sha :" "${{ github.sha }}"