name: Do Nothing At All

on:
  repository_dispatch:
    types: do-diddly-squat
jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo Doing Something...
